version: '2'

networks:
  sco_network:

services:
    ca-tls:
      container_name: ca-tls
      image: hyperledger/fabric-ca
      command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
      environment:
        - FABRIC_CA_SERVER_HOME=/hyperledger/fabric-ca/crypto
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_CSR_CN=ca-tls
        - FABRIC_CA_SERVER_CSR_HOSTS=192.168.20.2
        - FABRIC_CA_SERVER_DEBUG=true
      volumes:
        - /hyperledger/tls/ca:/hyperledger/fabric-ca
      networks:
        - sco_network
      ports:
        - 7052:7052
    rca-sco:
       container_name: rca-sco
       image: hyperledger/fabric-ca
       command: /bin/bash -c 'fabric-ca-server start -d -b rca-sco-admin:rca-sco-adminpw --port 7053'
       environment:
          - FABRIC_CA_SERVER_HOME=/hyperledger/fabric-ca/crypto
          - FABRIC_CA_SERVER_TLS_ENABLED=true
          - FABRIC_CA_SERVER_CSR_CN=rca-sco
          - FABRIC_CA_SERVER_CSR_HOSTS=192.168.20.2
          - FABRIC_CA_SERVER_DEBUG=true
       volumes:
          - /hyperledger/sco/ca:/hyperledger/fabric-ca
       networks:
          - sco_network
       ports:
          - 7053:7053
    rca-scm:
       container_name: rca-scm
       image: hyperledger/fabric-ca
       command: /bin/bash -c 'fabric-ca-server start -d -b rca-scm-admin:rca-scm-adminpw'
       environment:
          - FABRIC_CA_SERVER_HOME=/hyperledger/fabric-ca/crypto
          - FABRIC_CA_SERVER_TLS_ENABLED=true
          - FABRIC_CA_SERVER_CSR_CN=rca-scm
          - FABRIC_CA_SERVER_CSR_HOSTS=192.168.20.2
          - FABRIC_CA_SERVER_DEBUG=true
       volumes:
          - /hyperledger/scm/ca:/hyperledger/fabric-ca
       networks:
          - sco_network
       ports:
          - 7054:7054
    peer1-scm:
      container_name: peer1-scm
      image: hyperledger/fabric-peer
      environment:
        - CORE_PEER_ID=peer1-scm
        - CORE_PEER_ADDRESS=peer1-scm:7051
        - CORE_PEER_LOCALMSPID=scmMSP
        - CORE_PEER_MSPCONFIGPATH=/hyperledger/scm/peer1/msp
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=guide_fabric-ca
        - FABRIC_LOGGING_SPEC=debug
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/hyperledger/scm/peer1/tls-msp/signcerts/cert.pem
        - CORE_PEER_TLS_KEY_FILE=/hyperledger/scm/peer1/tls-msp/keystore/key.pem
        - CORE_PEER_TLS_ROOTCERT_FILE=/hyperledger/scm/peer1/tls-msp/tlscacerts/tls-192-168-20-2-7052.pem
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-scm:7051
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/scm/peer1
      volumes:
        - /var/run:/host/var/run
        - /hyperledger/scm/peer1:/hyperledger/scm/peer1
      networks:
        - sco_network
    orderer-sco:
      container_name: orderer-sco
      image: hyperledger/fabric-orderer
      environment:
        - ORDERER_HOME=/hyperledger/orderer
        - ORDERER_HOST=orderer-sco
        - ORDERER_GENERAL_LISTENADDRESS=192.168.20.2
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/hyperledger/sco/orderer/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=scoMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/hyperledger/sco/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_CERTIFICATE=/hyperledger/sco/orderer/tls-msp/signcerts/cert.pem
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/hyperledger/sco/orderer/tls-msp/keystore/key.pem
        - ORDERER_GENERAL_TLS_ROOTCAS=/hyperledger/sco/orderer/tls-msp/tlscacerts/tls-192-168-20-2-7052.pem
        - ORDERER_GENERAL_LOGLEVEL=debug
        - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      volumes:
        - /hyperledger/sco/orderer:/hyperledger/sco/orderer/
      networks:
        - sco_network
    cli-scm:
       container_name: cli-scm
       image: hyperledger/fabric-tools
       tty: true
       stdin_open: true
       environment:
         - GOPATH=/opt/gopath
         - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
         - FABRIC_LOGGING_SPEC=DEBUG
         - CORE_PEER_ID=cli-scm
         - CORE_PEER_ADDRESS=peer1-scm:7051
         - CORE_PEER_LOCALMSPID=scmMSP
         - CORE_PEER_TLS_ENABLED=true
         - CORE_PEER_TLS_ROOTCERT_FILE=/hyperledger/scm/peer1/tls-msp/tlscacerts/tls-192-168-20-2-7052.pem
         - CORE_PEER_MSPCONFIGPATH=/hyperledger/scm/peer1/msp
       working_dir: /opt/gopath/src/github.com/hyperledger/fabric/scm
       command: sh
       volumes:
         - /hyperledger/scm/peer1:/hyperledger/scm/peer1
         - /hyperledger/scm/peer1/assets/chaincode:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
         - /hyperledger/scm/admin:/hyperledger/scm/admin
       networks:
         - sco_network
